apiVersion: v1
kind: Secret
metadata:
  name: {{ template "k8s-backups-mongodb-sync.fullname" . }}
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}