apiVersion: batch/v1
kind: CronJob
metadata:
  name: k8s-backups-postgresql
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: Forbid
  suspend: false
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1

  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: k8s-backups-postgresql
              image: {{ .Values.image }}
              imagePullPolicy: {{ .Values.imagePullPolicy }}
              env:
                - name: PG_HOST
                  valueFrom:
                    secretKeyRef:
                      name: k8s-backups-postgresql
                      key: pgHost
                - name: PG_RESTORE_HOST
                  valueFrom:
                    secretKeyRef:
                      name: k8s-backups-postgresql
                      key: pgRestoreHost                      
                - name: PG_PORT
                  valueFrom:
                    secretKeyRef:
                      name: k8s-backups-postgresql
                      key: pgPort                     
                - name: PG_DATABASE
                  valueFrom:
                    secretKeyRef:
                      name: k8s-backups-postgresql
                      key: pgDatabase
                - name: PG_USER
                  valueFrom:
                    secretKeyRef:
                      name: k8s-backups-postgresql
                      key: pgUser
                - name: PG_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: k8s-backups-postgresql
                      key: pgPassword                      
                - name: BUCKET_URI
                  valueFrom:
                    secretKeyRef:
                      name: k8s-backups-postgresql
                      key: bucketUri
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: k8s-backups-postgresql
                      key: awsAccessKeyId
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: k8s-backups-postgresql
                      key: awsSecretAccessKey
                - name: AWS_DEFAULT_REGION
                  valueFrom:
                    secretKeyRef:
                      name: k8s-backups-postgresql
                      key: awsDefaultRegion
                - name: S3_ENDPOINT_URL
                  valueFrom:
                    secretKeyRef:
                      name: k8s-backups-postgresql
                      key: s3EndpointUrl
                - name: PASSWORD_7ZIP
                  valueFrom:
                    secretKeyRef:
                      name: k8s-backups-postgresql
                      key: password7Zip
