{{- if or .Values.prescript .Values.postscript }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "k8s-backups-mongodb.fullname" . }}
data:
  {{- if .Values.prescript}}
  prescript.sh: {{ .Values.prescript | quote }}
  {{- end }}
  {{- if .Values.prescript}}
  postscript.sh: {{ .Values.postscript | quote }}
  {{- end }}
{{- end }}