apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ template "k8s-backups-mongodb.fullname" . }}
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: Forbid
  suspend: false
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1

  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: {{ .Chart.Name }}
              image: {{ .Values.image }}
              imagePullPolicy: {{ .Values.imagePullPolicy }}
              env:
                - name: MONGODB_URI
                  valueFrom:
                    secretKeyRef:
                      name: {{ template "k8s-backups-mongodb.secret" . }}
                      key: mongoDbUri
                - name: MONGODB_RESTORE_URI
                  valueFrom:
                    secretKeyRef:
                      name: {{ template "k8s-backups-mongodb.secret" . }}
                      key: mongoRestoreDbUri
                - name: MONGODB_OPLOG
                  value: {{ .Values.withOplog | quote }}
                - name: MONGODB_CONVERTLEGACYINDEXES_FLAG
                  value: {{ .Values.convertLegacyIndexes | quote }}                 
                - name: MONGODB_NOINDEXRESTORE_FLAG
                  value: {{ .Values.noIndexRestore | quote }}    
                - name: BUCKET_URI
                  valueFrom:
                    secretKeyRef:
                      name: {{ template "k8s-backups-mongodb.secret" . }}
                      key: bucketUri
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: {{ template "k8s-backups-mongodb.secret" . }}
                      key: awsAccessKeyId
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ template "k8s-backups-mongodb.secret" . }}
                      key: awsSecretAccessKey
                - name: AWS_DEFAULT_REGION
                  valueFrom:
                    secretKeyRef:
                      name: {{ template "k8s-backups-mongodb.secret" . }}
                      key: awsDefaultRegion
                - name: S3_ENDPOINT_URL
                  valueFrom:
                    secretKeyRef:
                      name: {{ template "k8s-backups-mongodb.secret" . }}
                      key: s3EndpointUrl
                - name: PASSWORD_7ZIP
                  valueFrom:
                    secretKeyRef:
                      name: {{ template "k8s-backups-mongodb.secret" . }}
                      key: password7Zip
