# Default values for k8s-backups-postgresql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

schedule: "0 0 * * *"
image: "wcgomes/k8s-backups-postgresql:0.2.0"

imagePullPolicy: IfNotPresent

secrets:
  pgHost: ""
  pgRestoreHost: ""
  pgPort: "5432"
  pgDatabase: ""
  pgUser: ""
  pgPassword: ""
  bucketUri: ""
  awsAccessKeyId: ""
  awsSecretAccessKey: ""
  s3EndpointUrl: ""
  awsDefaultRegion: ""
  password7Zip: ""
