# Default values for k8s-backups-postgresql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

schedule: "0 0 * * *"
image: "wcgomes/k8s-backups-postgresql:0.3.1"

imagePullPolicy: IfNotPresent

# use a existing secret
existingSecret: ""

# create a new secret with the specified values
secrets:
  pgHost: ""
  pgRestoreHost: ""
  pgPort: "5432"
  pgDatabase: ""
  pgUser: ""
  pgPassword: ""
  bucketUri: ""
  awsAccessKeyId: ""
  awsSecretAccessKey: ""
  s3EndpointUrl: ""
  awsDefaultRegion: ""
  password7Zip: ""

# shell script to run before backup is restored
# use it stop services or make database adjustments to another enviroment
# prescript: |
#    #!/bin/bash
#    echo "Initialing script..."
#    # More commands here
#    echo "Script completed."
prescript: ""

# shell script to run after backup is restored
# use it restart services or make database adjustments to another enviroment
# postscript: |
#    #!/bin/bash
#    echo "Initialing script..."
#    # More commands here
#    echo "Script completed."
postscript: ""