# Default values for k8s-backups-mongodb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

schedule: "0 0 * * *"
image: "wcgomes/k8s-backups-mongodb:0.5.0"

imagePullPolicy: IfNotPresent

# https://www.mongodb.com/pt-br/docs/database-tools/mongodump/#options
dumpOptionalFlags: ""

# https://www.mongodb.com/pt-br/docs/database-tools/mongorestore/#options
restoreOptionalFlags: ""

# use a existing secret
existingSecret: ""

# create a new secret with the specified values
secrets:
  mongoDbUri: ""
  mongoRestoreDbUri: ""
  bucketUri: ""
  awsAccessKeyId: ""
  awsSecretAccessKey: ""
  s3EndpointUrl: ""
  awsDefaultRegion: ""
  password7Zip: ""

# shell script to run before backup is restored
# use it stop services or make database adjustments to another enviroment
# prescript: |
#    #!/bin/bash
#    echo "Initialing script..."
#    # More commands here
#    echo "Script completed."
prescript: ""

# shell script to run after backup is restored
# use it restart services or make database adjustments to another enviroment
# postscript: |
#    #!/bin/bash
#    echo "Initialing script..."
#    # More commands here
#    echo "Script completed."
postscript: ""