# Default values for k8s-backups-mongodb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

schedule: "0 0 * * *"
image: "wcgomes/k8s-backups-mongodb:0.2.0"

imagePullPolicy: IfNotPresent

withOplog: "true"

secrets:
  mongoDbUri: ""
  mongoRestoreDbUri: ""
  bucketUri: ""
  awsAccessKeyId: ""
  awsSecretAccessKey: ""
  s3EndpointUrl: ""
  awsDefaultRegion: ""
  password7Zip: ""
